#!/bin/bash

FILES=".bashrc .gitconfig .profile .tmux.conf .zshenv .zshrc"
DOTFILE_DIR=$(pwd)

for FILE in $FILES; do
  ln -sf $DOTFILE_DIR/$FILE ~/$FILE
done

ln -sf $DOTFILE_DIR/init.vim ~/.config/nvim/init.vim
ln -sf $DOTFILE_DIR/.ycm_extra_conf.py ~/.config/nvim/.ycm_extra_conf.py
